### ISSUE TITLE
我读了你的博客文章……

### ISSUE THREAD

**Issue by Artoria2e5** [Tarantiner/coord#1]
看到你又是 F12 又是选元素的，想问问你真的就没看到我那个 demo 页面上最下面那个 "Powered by PRCoords" 吗……

https://github.com/Artoria2e5/PRCoords

……当然有人喜欢我写的这鬼东西我还挺开心的。

**Comment by Tarantiner** [comment]
哈哈，原来还真没注意到，我是从维基百科点进那个网页的，没想到背后还有一个现成的库，不过过程复杂点也好，一方面这是一个很好的chrome调试案例，另一方面也熟悉下go语言。另外，大佬真的厉害啊，应该是专门做地理测绘方面的吧



---原始邮件---
发件人: "Mingye ***@***.***&gt;
发送时间: 2021年4月17日(周六) 晚上7:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Tarantiner/coord] 我读了你的博客文章…… (#1)




 
看到你又是 F12 又是选元素的，想问问你真的就没看到我那个 demo 页面上最下面那个 "Powered by PRCoords" 吗……
 
https://github.com/Artoria2e5/PRCoords

**Comment by Artoria2e5** [comment]
不是啦，我纯业余的……
